[dependencies]
vector = "0.4.1"
map = "9.0.1"
base = "0.12.1"
prng = "0.0.5"
account = "1.0.1"
itertools = "0.2.1"
rechain = "1.1.5"
mosup = "0.1.1"
devefi = "../devefi"
devefi_swap = "../devefi_swap/"
